# Generated by Django 5.1.1 on 2024-10-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
