# Generated by Django 5.1.1 on 2024-10-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='regiao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='uf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
